### ISSUE TITLE
xRDP and RealVNC Preview Do Not Co-Exist

### ISSUE THREAD

**Issue by Saijin-Naib** [RealVNC/raspi-preview#4]
As stated, if a user previously has xRPD installed and then installs RealVNC preview, it will break xRDP and RealVNC both. Neither will accept incoming connections nor render the desktop of the device.

Uninstalling vnc4server (a dependency of xRPD) is insufficient to restore functionality. Uninstalling xRDP is also not sufficient to restore functionality.

It seems the install fails while looking for a $DISPLAY variable. doing a set $DISPLAY=:0.0 before install doesn't fix it, either:
$ sudo dpkg -i VNC-Server-5.3.1-raspi-alpha1.deb
(Reading database ... 121310 files and directories currently installed.)
Preparing to unpack VNC-Server-5.3.1-raspi-alpha1.deb ...

(gconftool-2:1190): GConf-WARNING **: Client failed to connect to the D-BUS daemon:
Unable to autolaunch a dbus-daemon without a $DISPLAY for X11
Unpacking realvnc-vnc-server (5.3.1.18206) over (5.3.1.18206) ...
Setting up realvnc-vnc-server (5.3.1.18206) ...
Updating /etc/pam.d/vncserver
Updating /etc/pam.conf... done
Looking for font path... not found.
Original config file "/etc/vnc/config.old" preserved

Installing Raspberry Pi license (VNC Personal)
Please note that this is only valid for non-commercial use on Raspberry Pi devices.
See https://www.realvnc.com/products/vnc/ for information about VNC licenses.
License key <RasPi-Alpha> has been successfully applied.

Installed systemd unit for VNC Server in Service Mode daemon
Start or stop the service with:
  systemctl (start|stop) vncserver-x11-serviced.service
Mark or unmark the service to be started at boot time with:
  systemctl (enable|disable) vncserver-x11-serviced.service

Installed systemd unit for VNC Server in Virtual Mode daemon
Start or stop the service with:
  systemctl (start|stop) vncserver-virtuald.service
Mark or unmark the service to be started at boot time with:
  systemctl (enable|disable) vncserver-virtuald.service

(gconftool-2:1338): GConf-WARNING **: Client failed to connect to the D-BUS daemon:
Unable to autolaunch a dbus-daemon without a $DISPLAY for X11
gconfd-2: no process found
Processing triggers for gconf2 (3.2.6-3) ...
Processing triggers for hicolor-icon-theme (0.13-1) ...
Processing triggers for man-db (2.7.0.2-5) ...
Processing triggers for shared-mime-info (1.3-1) ...
Processing triggers for gnome-menus (3.13.3-6) ...
Processing triggers for desktop-file-utils (0.22-1) ...
Processing triggers for mime-support (3.58) ...

**Comment by sconemad** [comment]
Hi Saijin-Naib,

Thanks very much for your feedback.

You're right, our package (realvnc-vnc-server) cannot co-exist with the vnc4server package unfortunately, since they install some of the same binaries. The same goes for other VNC server packages, e.g. tightvncserver.

You should be able to sort things out on your device by uninstalling all VNC server packages (i.e. vnc4server and realvnc-vnc-server), then reinstalling the one you want.

Also note that we don't automatically start or stop our services when our package is installed or uninstalled, so you'll need to do that manually at the moment.

The warnings about $DISPLAY I believe are harmless and not related to this issue.

**Comment by Saijin-Naib** [comment]
Scone,
Thanks for the reply. I did have to remove it unfortunately. Do you think that in the future your package could be compatible with xRDP so the user has the flexibility of using both VNC and RDP on the same server? That'd be quite helpful in increasing the pool of clients that can connect natively.

**Comment by sconemad** [comment]
Hi Saijin-Naib,

Yes, we'll look into this to see if there is anything more we can do.

Thanks again for your feedback.

**Comment by sconemad** [comment]
In the latest version (5.3.2.22164, which is now available in Raspbian), we have made the realvnc-vnc-server package conflict with vnc4server. While this doesn't solve the problem of allowing these to coexist, it does prevent people from getting their system into a confused state.

At the moment, in order to use xrdp, should install vnc4server (which will remove realvnc-vnc-server).

**Comment by Ruffio** [comment]
Has this issue been resolved?

**Comment by nicogies** [comment]
Hello,
I have a similar issue.
Having before `tightvnc` installed on my raspeberry pi,, I removed it to install real-vnc server and end with the same error:
```sh
$ sudo apt-get install --reinstall  realvnc-vnc-server
Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 0 not upgraded.
Need to get 0 B/5,107 kB of archives.
After this operation, 0 B of additional disk space will be used.
(Reading database ... 142369 files and directories currently installed.)
Preparing to unpack .../realvnc-vnc-server_6.0.3.27095_armhf.deb ...

(gconftool-2:9962): GConf-WARNING **: Client failed to connect to the D-BUS daemon:
Unable to autolaunch a dbus-daemon without a $DISPLAY for X11
Unpacking realvnc-vnc-server (6.0.3.27095) over (6.0.3.27095) ...
Processing triggers for gconf2 (3.2.6-3) ...
Processing triggers for gnome-menus (3.13.3-6) ...
Processing triggers for desktop-file-utils (0.22-1) ...
Processing triggers for mime-support (3.58) ...
Processing triggers for man-db (2.7.0.2-5) ...
Processing triggers for shared-mime-info (1.3-1) ...
Processing triggers for hicolor-icon-theme (0.13-1) ...
Setting up realvnc-vnc-server (6.0.3.27095) ...
Updating /etc/pam.d/vncserver
Updating /etc/pam.conf... done
Looking for font path... not found.
Installed systemd unit for VNC Server in Service Mode daemon
Start or stop the service with:
  systemctl (start|stop) vncserver-x11-serviced.service
Mark or unmark the service to be started at boot time with:
  systemctl (enable|disable) vncserver-x11-serviced.service

Installed systemd unit for VNC Server in Virtual Mode daemon
Start or stop the service with:
  systemctl (start|stop) vncserver-virtuald.service
Mark or unmark the service to be started at boot time with:
  systemctl (enable|disable) vncserver-virtuald.service


(gconftool-2:10453): GConf-WARNING **: Client failed to connect to the D-BUS daemon:
Unable to autolaunch a dbus-daemon without a $DISPLAY for X11
gconfd-2: no process found
```
Is there an existing workaround ?
Thanks!

**Comment by sconemad** [comment]
Hi @nicogies,

The output you posted doesn't show an error. The warnings shown are produced by the various methods we use to determine the X server's font path, but are nothing to worry about.

The server should be installed and working at this point, did you try to enable it via raspi-config?

The original problem reported in this issue is about using the RealVNC server package with xRDP. There are some workarounds for this - see the following comment on the Raspberry Pi forum:
https://www.raspberrypi.org/forums/viewtopic.php?p=1054659#p1054659

**Comment by minkustree** [comment]
The preview has now ended, and a full version of the software is included with Raspbian and available from https://realvnc.com. We will unfortunately not be making any further comments on issues reported here.
