### ISSUE TITLE
OpenElec Kodi Cannot Install

### ISSUE THREAD

**Issue by thegnnu** [RealVNC/raspi-preview#6]
Anyone found how to install in OpenElec as I have only got as far as "dpkg -i VNC-Server-5.3.1-raspi-alpha1.deb" OpenElec come back with a fault of "dpkg: not found"  
curl command did work anybody have any suggestions pleas.
Works great on normal Pi with the camera just what I wanted. Well done the Realvnc Team
Terry

**Comment by sconemad** [comment]
Hi Terry,

Thanks very much for your feedback.

Unfortunately we only support Raspbian at the moment. There are several issues which would prevent VNC Server running on OpenELEC, the first being the lack of support for installing Debian packages, as you have found. Assuming you copied the binaries into place via some other means, you would also run into problems due to missing X11 libraries that the software depends on which are not present on OpenELEC. It may be possible to install these, but it's not a simple process. We are investigating if there is a way we can support this.

However, you can simply install Kodi on Raspbian (apt-get install kodi), and provided you launch it from the console (i.e. not from the X11 desktop), it appears to work well with VNC Server.

**Comment by Ruffio** [comment]
I don't see a way that this is ever going to be 'resolved'. It should be closed...
