### ISSUE TITLE
Minecraft not working correct Raspberry Pi 3 with VNC 5.3.2 (or older)

### ISSUE THREAD

**Issue by peterwitte** [RealVNC/raspi-preview#7]
Just installed VNC server on my rapsberry pi 3 (with the lateste Jessy release)
When opening VNC viewer on my windows 10 laptop, everything seems to work just fine.
However, when i trie to play minecraft (remote with VNC viewer) the startscreen appears on my windows PC, and the screen with the games om my rapsberry pi (dual screens), dual screens....???
Just can't play the game remote

What is going wrong?
I installed VNC: 5.3.2 (and the version 5.2.1)
- curl -L -o VNC.tar.gz https://www.realvnc.com/download/binary/latest/debian/arm/
  tar xvf VNC.tar.gz
- sudo dpkg -i <VNC-Server-package-name>.deb <VNC-Viewer-package-name>.deb
  apllied my license
- sudo vnclicense -add <license-key>
  started server
- sudo systemctl start vncserver-x11-serviced.service

optimised VNC viewer.
see the attached files
![screen raspberry pi on windows client](https://cloud.githubusercontent.com/assets/20141045/16356814/6e653ac6-3ae5-11e6-8353-f505f7d63cb9.jpg)

**Comment by sconemad** [comment]
Hi Peter,

You need to download the alpha version from the GitHub Releases page. The version on the RealVNC website doesn't yet support Minecraft.

**Comment by peterwitte** [comment]
Hi Andrew,

I Just made a copy of my original SD Card and tried it again with the apha version.
It does work now. (little bit slow though)

I think i opened to many server sessions yesterday
when starting VNC Viewer with 192.168.178.51:**0** i will get a the same  session as seen on the Pi.
When starting VNC Viewer with 192.168.178.51:**1** i get a (new) session which is not the same as on my screen connected to my Pi.

Problem solved, Thanks.

![minecraft screen](https://cloud.githubusercontent.com/assets/20141045/16361568/fc56fec8-3b94-11e6-8031-8b3090a969f3.jpg)

**Comment by sconemad** [comment]
Hi Peter,

Thanks for the feedback. I'm glad you were able to get it working.

FYI: VNC Server has two distinct modes of operation: service mode, where you see what would be on the screen of the device; and virtual mode, where we create a separate in-memory desktop. Service mode is started automatically as a system service, and usually uses desktop :0 (the default). Virtual mode is usually started manually by running the "vncserver" command, and creates desktops numbered from :1 onwards.

So it sounds like you had a virtual mode server running on display :1 in addition to the service mode server. Minecraft will not run in a virtual mode desktop, since it requires the use of the GPU, which virtual mode does not have access to.

See https://www.realvnc.com/products/vnc/documentation/5.3/modes/ for more information on server modes.
